export const BASE_URL = "http://3.133.64.67:8196/PetRegistration"; //Temporarily using field; Enter Backend URL here e.g. http://3.133.64.67:8164/generated_app
export const PATH_APPOINTMENT = "/Appointments";
export const PATH_PETOWNER = "/PetOwners";
export const PATH_VETERIAN = "/Veterians";
export const PATH_VISIT = "/Visits";
export const PATH_VACCINESCHEDULER = "/VaccineSchedulers";
export const PATH_IMAGE = "/Images";
export const PATH_PET = "/Pets";
export const PATH_VISITSCHEDULER = "/VisitSchedulers";
